spring:
  security:
    basic:
      enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foundroom
    username: postgres
    password: password
    testOnBorrow: true
    validationQuery: 'SELECT 1'

logging:
  level:
    \*: INFO

server:
  port: 8084

swagger:
  basePath: /api
  apiVersion: 1.0